
export const MOVIE_SLUG = {
  PHIM_MOI: "phim-moi",
  PHIM_BO: "phim-bo",
  PHIM_LE: "phim-le",
  TV_SHOWS: "tv-shows",
  HOAT_HINH: "hoat-hinh",
  PHIM_VIETSUB: "phim-vietsub",
  PHIM_THUYET_MINH: "phim-thuyet-minh",
  PHIM_LONG_TIEN: "phim-long-tien",
  PHIM_BO_DANG_CHIEU: "phim-bo-dang-chieu",
  PHIM_BO_HOAN_THANH: "phim-bo-hoan-thanh",
  PHIM_SAP_CHIEU: "phim-sap-chieu",
  SUBTEAM: "subteam",
  PHIM_CHIEU_RAP: "phim-chieu-rap"
} as const

export const MOVIE_SLUG_LABEL: Record<string, string> = {
  "phim-moi": "Phim mới",
  "phim-bo": "Phim bộ",
  "phim-le": "Phim lẻ",
  "tv-shows": "TV Shows",
  "hoat-hinh": "Hoạt hình",
  "phim-vietsub": "Phim Vietsub",
  "phim-thuyet-minh": "Phim thuyết minh",
  "phim-long-tien": "Phim lồng tiếng",
  "phim-bo-dang-chieu": "Phim bộ đang chiếu",
  "phim-bo-hoan-thanh": "Phim bộ hoàn thành",
  "phim-sap-chieu": "Phim sắp chiếu",
  "subteam": "Subteam",
};



export const SORT_FIELD = {
  MODIFIED_TIME: "modified.time",
  YEAR: "year",
  ID: "_id",
} as const

export const SORT_TYPE = {
  DESC: "desc",
  ASC: "asc",
} as const

export const CATEGORY = {
    HANH_DONG: "hanh-dong",
    TINH_CAM: "tinh-cam",
    HAI_HUOC: "hai-huoc",
    CO_TRANG: "co-trang",
    TAM_LY: "tam-ly",
    HINH_SU: "hinh-su",
    CHIEN_TRANH: "chien-tranh",
    THE_THAO: "the-thao",
    VO_THUAT: "vo-thuat",
    VIEN_TUONG: "vien-tuong",
    PHIEU_LUU: "phieu-luu",
    KHOA_HOC: "khoa-hoc",
    KINH_DI: "kinh-di",
    AM_NHAC: "am-nhac",
    THAN_THOAI: "than-thoai",
    TAI_LIEU: "tai-lieu",
    GIA_DINH: "gia-dinh",
    CHINH_KICH: "chinh-kich",
    BI_AN: "bi-an",
    HOC_DUONG: "hoc-duong",
    KINH_DIEN: "kinh-dien",
} as const

export const COUNTRY = {
    VIET_NAM: "viet-nam",
    HAN_QUOC: "han-quoc",
    TRUNG_QUOC: "trung-quoc",
    NHAT_BAN: "nhat-ban",
    THAI_LAN: "thai-lan",
    AU_MY: "au-my",
    DAI_LOAN: "dai-loan",
    HONG_KONG: "hong-kong",
    AN_DO: "an-do",
    ANH: "anh",
    PHAP: "phap",
    CANADA: "canada",
    QUOC_GIA_KHAC: "quoc-gia-khac",
    DUC: "duc",
    TAY_BAN_NHA: "tay-ban-nha",
    THO_NHI_KY: "tho-nhi-ky",
    HA_LAN: "ha-lan",
    INDONESIA: "indonesia",
    NGA: "nga",
    MEXICO: "mexico",
    BA_LAN: "ba-lan",
    UC: "uc",
    THUY_DIEN: "thuy-dien",
    MALAYSIA: "malaysia",
    BRAZIL: "brazil",
    PHILIPPINES: "philippines",
    BO_DAO_NHA: "bo-dao-nha",
    Y: "y",
    DAN_MACH: "dan-mach",
    UAE: "uae",
    NA_UY: "na-uy",
    THUY_SI: "thuy-si",
    CHAU_PHI: "chau-phi",
    NAM_PHI: "nam-phi",
    UKRAINA: "ukraina",
    A_RAP_XE_UT: "a-rap-xe-ut",
    BI: "bi",
    IRELAND: "ireland",
    COLOMBIA: "colombia",
    PHAN_LAN: "phan-lan",
    CHILE: "chile",
    HY_LAP: "hy-lap",
    NIGERIA: "nigeria",
    ARGENTINA: "argentina",
    SINGAPORE: "singapore",
} as const

export const GRADIENTS = {
    PURPLE: "from-purple-400 via-purple-500 to-white",
    YELLOW_PURPLE: "from-yellow-400 via-purple-500 to-white",
    PINK_RED: "from-pink-400 via-red-500 to-white",
    BLUE_INDIGO: "from-blue-400 via-indigo-500 to-white",
    GREEN_TEAL: "from-green-400 via-teal-500 to-white",
    ORANGE_RED: "from-orange-400 via-red-500 to-white",
    TEAL_CYAN: "from-teal-400 via-cyan-500 to-white",
    LIME_GREEN: "from-lime-400 via-green-500 to-white",
    INDIGO_BLUE: "from-indigo-400 via-blue-500 to-white",
    GRAY_DARK: "from-gray-400 via-gray-700 to-white",
} as const
