export const mockMovies = [
  {
    id: 1,
    title: "The Dark Knight",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2008,
    rating: 9.0,
    duration: "2h 32m",
    genres: ["action", "crime", "drama"],
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    trailerUrl: "EXeTwQWrcwY",
    type: "movie",
    country: "usa",
  },
  {
    id: 2,
    title: "Inception",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2010,
    rating: 8.8,
    duration: "2h 28m",
    genres: ["action", "sci-fi", "thriller"],
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    trailerUrl: "YoHD9XEInc0",
    type: "movie",
    country: "usa",
  },
  {
    id: 3,
    title: "Parasite",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2019,
    rating: 8.6,
    duration: "2h 12m",
    genres: ["drama", "thriller"],
    description:
      "A poor family schemes to become employed by a wealthy family and infiltrate their household by posing as unrelated, highly qualified individuals.",
    trailerUrl: "5xH0HfJHsaY",
    type: "movie",
    country: "korea",
  },
  {
    id: 4,
    title: "Avengers: Endgame",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2019,
    rating: 8.4,
    duration: "3h 1m",
    genres: ["action", "adventure", "sci-fi"],
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more.",
    trailerUrl: "TcMBFSGVi1c",
    type: "movie",
    country: "usa",
  },
  {
    id: 5,
    title: "Spirited Away",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2001,
    rating: 9.2,
    duration: "2h 5m",
    genres: ["animation", "adventure", "family"],
    description:
      "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits.",
    trailerUrl: "ByXuk9QqQkk",
    type: "movie",
    country: "japan",
  },
  {
    id: 6,
    title: "The Godfather",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1972,
    rating: 9.2,
    duration: "2h 55m",
    genres: ["crime", "drama"],
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    trailerUrl: "sY1S34973zA",
    type: "movie",
    country: "usa",
  },
  {
    id: 7,
    title: "Pulp Fiction",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1994,
    rating: 8.9,
    duration: "2h 34m",
    genres: ["crime", "drama"],
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    trailerUrl: "s7EdQ4FqbhY",
    type: "movie",
    country: "usa",
  },
  {
    id: 8,
    title: "Interstellar",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2014,
    rating: 8.6,
    duration: "2h 49m",
    genres: ["adventure", "drama", "sci-fi"],
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    trailerUrl: "zSWdZVtXT7E",
    type: "movie",
    country: "usa",
  },
  {
    id: 9,
    title: "The Matrix",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1999,
    rating: 8.7,
    duration: "2h 16m",
    genres: ["action", "sci-fi"],
    description:
      "A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.",
    trailerUrl: "vKQi3bBA1y8",
    type: "movie",
    country: "usa",
  },
  {
    id: 10,
    title: "Goodfellas",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1990,
    rating: 8.7,
    duration: "2h 26m",
    genres: ["biography", "crime", "drama"],
    description:
      "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
    trailerUrl: "qo5jJpHtI1Y",
    type: "movie",
    country: "usa",
  },
  {
    id: 11,
    title: "Forrest Gump",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1994,
    rating: 8.8,
    duration: "2h 22m",
    genres: ["drama", "romance"],
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold from the perspective of an Alabama man.",
    trailerUrl: "bLvqoHBptjg",
    type: "movie",
    country: "usa",
  },
  {
    id: 12,
    title: "Fight Club",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1999,
    rating: 8.8,
    duration: "2h 19m",
    genres: ["drama"],
    description:
      "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much more.",
    trailerUrl: "qtRKdVHc-cE",
    type: "movie",
    country: "usa",
  },
  {
    id: 13,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2001,
    rating: 8.8,
    duration: "2h 58m",
    genres: ["adventure", "drama", "fantasy"],
    description:
      "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
    trailerUrl: "V75dMMIW2B4",
    type: "movie",
    country: "usa",
  },
  {
    id: 14,
    title: "Star Wars: Episode IV - A New Hope",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1977,
    rating: 8.6,
    duration: "2h 1m",
    genres: ["adventure", "fantasy", "sci-fi"],
    description:
      "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station.",
    trailerUrl: "vZ734NWnAHA",
    type: "movie",
    country: "usa",
  },
  {
    id: 15,
    title: "The Shawshank Redemption",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 1994,
    rating: 9.3,
    duration: "2h 22m",
    genres: ["drama"],
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    trailerUrl: "6hB3S9bIaco",
    type: "movie",
    country: "usa",
  },
  {
    id: 16,
    title: "Breaking Bad",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2008,
    rating: 9.5,
    duration: "47m",
    genres: ["crime", "drama", "thriller"],
    description:
      "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.",
    trailerUrl: "HhesaQXLuRY",
    type: "series",
    country: "usa",
  },
  {
    id: 17,
    title: "Game of Thrones",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2011,
    rating: 9.3,
    duration: "57m",
    genres: ["action", "adventure", "drama"],
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    trailerUrl: "rlR4PJn8b8I",
    type: "series",
    country: "usa",
  },
  {
    id: 18,
    title: "Stranger Things",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2016,
    rating: 8.7,
    duration: "51m",
    genres: ["drama", "fantasy", "horror"],
    description:
      "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.",
    trailerUrl: "b9EkMc79ZSU",
    type: "series",
    country: "usa",
  },
  {
    id: 19,
    title: "The Crown",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2016,
    rating: 8.6,
    duration: "58m",
    genres: ["biography", "drama", "history"],
    description:
      "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
    trailerUrl: "JWtnJjn6ng0",
    type: "series",
    country: "uk",
  },
  {
    id: 20,
    title: "The Witcher",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2019,
    rating: 8.2,
    duration: "60m",
    genres: ["action", "adventure", "drama"],
    description:
      "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    trailerUrl: "ndl1W4ltcmg",
    type: "series",
    country: "usa",
  },
  {
    id: 21,
    title: "Money Heist",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2017,
    rating: 8.3,
    duration: "70m",
    genres: ["action", "crime", "mystery"],
    description:
      "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    trailerUrl: "p_PJbmrX4uk",
    type: "series",
    country: "spain",
  },
  {
    id: 22,
    title: "Squid Game",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2021,
    rating: 8.0,
    duration: "60m",
    genres: ["action", "drama", "mystery"],
    description:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games for a tempting prize, but the stakes are deadly.",
    trailerUrl: "oqxAJKy0ii4",
    type: "series",
    country: "korea",
  },
  {
    id: 23,
    title: "The Mandalorian",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2019,
    rating: 8.7,
    duration: "40m",
    genres: ["action", "adventure", "sci-fi"],
    description:
      "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.",
    trailerUrl: "aOC8E8z_ifw",
    type: "series",
    country: "usa",
  },
  {
    id: 24,
    title: "Wednesday",
    poster: "/placeholder.svg?height=450&width=300",
    backdrop: "/placeholder.svg?height=720&width=1280",
    year: 2022,
    rating: 8.1,
    duration: "50m",
    genres: ["comedy", "crime", "family"],
    description:
      "Follows Wednesday Addams' years as a student at Nevermore Academy, where she attempts to master her emerging psychic ability.",
    trailerUrl: "Di310WS8zLk",
    type: "series",
    country: "usa",
  },
]

export const mockComments = [
  {
    id: 1,
    user: "MovieBuff2023",
    avatar: "/placeholder.svg?height=40&width=40",
    comment:
      "Absolutely incredible movie! The cinematography and acting were top-notch. Definitely one of my favorites this year.",
    timestamp: "2 hours ago",
  },
  {
    id: 2,
    user: "CinemaLover",
    avatar: "/placeholder.svg?height=40&width=40",
    comment:
      "Great storyline and character development. The plot twists kept me on the edge of my seat throughout the entire film.",
    timestamp: "5 hours ago",
  },
  {
    id: 3,
    user: "FilmCritic99",
    avatar: "/placeholder.svg?height=40&width=40",
    comment:
      "While the visuals were stunning, I felt the pacing could have been better in the second act. Overall still a solid watch.",
    timestamp: "1 day ago",
  },
  {
    id: 4,
    user: "ActionFan",
    avatar: "/placeholder.svg?height=40&width=40",
    comment:
      "The action sequences were phenomenal! The choreography and special effects really brought the scenes to life.",
    timestamp: "2 days ago",
  },
  {
    id: 5,
    user: "DramaQueen",
    avatar: "/placeholder.svg?height=40&width=40",
    comment:
      "Such an emotional journey. The performances were so authentic that I found myself completely invested in the characters.",
    timestamp: "3 days ago",
  },
]
